In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
apartments_2023_08 = pd.read_csv('../data/raw/apartments_pl_2023_08.csv').assign(date='08.2023')
apartments_2023_09 = pd.read_csv('../data/raw/apartments_pl_2023_09.csv').assign(date='09.2023')
apartments_2023_10 = pd.read_csv('../data/raw/apartments_pl_2023_10.csv').assign(date='10.2023')
apartments_2023_11 = pd.read_csv('../data/raw/apartments_pl_2023_11.csv').assign(date='11.2023')
apartments_2023_12 = pd.read_csv('../data/raw/apartments_pl_2023_12.csv').assign(date='12.2023')

apartments_2024_01 = pd.read_csv('../data/raw/apartments_pl_2024_01.csv').assign(date='01.2024')
apartments_2024_02 = pd.read_csv('../data/raw/apartments_pl_2024_02.csv').assign(date='02.2024')
apartments_2024_03 = pd.read_csv('../data/raw/apartments_pl_2024_03.csv').assign(date='03.2024')
apartments_2024_04 = pd.read_csv('../data/raw/apartments_pl_2024_04.csv').assign(date='04.2024')
apartments_2024_05 = pd.read_csv('../data/raw/apartments_pl_2024_05.csv').assign(date='05.2024')
apartments_2024_06 = pd.read_csv('../data/raw/apartments_pl_2024_06.csv').assign(date='06.2024')

In [15]:
df = pd.concat([apartments_2023_08,apartments_2023_09,apartments_2023_10,apartments_2023_11, apartments_2023_12, apartments_2024_01,apartments_2024_02,apartments_2024_03,apartments_2024_04,apartments_2024_05,apartments_2024_06])

df.head()

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,date
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3.0,4.0,10.0,1980.0,53.378933,14.625296,...,condominium,concreteSlab,NaN,yes,yes,yes,no,yes,415000,08.2023
1,accbe77d4b360fea9735f138a50608dd,szczecin,blockOfFlats,36.00,2.0,8.0,10.0,NaN,53.442692,14.559690,...,cooperative,concreteSlab,NaN,no,yes,yes,no,yes,395995,08.2023
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,tenement,73.02,3.0,2.0,3.0,NaN,53.452222,14.553333,...,condominium,brick,NaN,no,no,no,no,no,565000,08.2023
3,0a68cd14c44ec5140143ece75d739535,szczecin,tenement,87.60,3.0,2.0,3.0,NaN,53.435100,14.532900,...,condominium,brick,NaN,yes,yes,no,no,yes,640000,08.2023
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,blockOfFlats,66.00,3.0,1.0,3.0,NaN,53.410278,14.503611,...,condominium,NaN,NaN,no,no,no,no,no,759000,08.2023

In [16]:
df = df[(df['city'] == 'warszawa')].copy()
df.drop(columns=['city', 'id'], inplace = True)

df.head()

,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,centreDistance,poiCount,...,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,date
12493,apartmentBuilding,112.80,4.0,2.0,5.0,1998.0,52.236141,20.987732,1.19,73.0,...,cooperative,brick,premium,yes,yes,yes,no,no,2050000,08.2023
12494,blockOfFlats,54.64,2.0,4.0,5.0,1999.0,52.185400,20.959800,5.95,10.0,...,condominium,brick,NaN,no,no,yes,no,no,869000,08.2023
12495,blockOfFlats,60.00,3.0,NaN,5.0,2007.0,52.260800,21.058970,4.97,16.0,...,condominium,NaN,premium,no,yes,yes,no,no,700000,08.2023
12496,blockOfFlats,28.80,2.0,9.0,11.0,1978.0,52.238200,20.908600,6.51,19.0,...,condominium,concreteSlab,NaN,yes,yes,yes,no,yes,435000,08.2023
12497,apartmentBuilding,122.70,5.0,3.0,3.0,1998.0,52.168100,21.079000,8.74,12.0,...,condominium,brick,NaN,yes,yes,no,yes,no,1500000,08.2023

## Data Cleaning

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59246 entries, 12493 to 20563
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  44412 non-null  object
 1   squareMeters          59246 non-null  float64
 2   rooms                 59246 non-null  float64
 3   floor                 50210 non-null  float64
 4   floorCount            58673 non-null  float64
 5   buildYear             53648 non-null  float64
 6   latitude              59246 non-null  float64
 7   longitude             59246 non-null  float64
 8   centreDistance        59246 non-null  float64
 9   poiCount              59246 non-null  float64
 10  schoolDistance        59242 non-null  float64
 11  clinicDistance        58977 non-null  float64
 12  postOfficeDistance    59203 non-null  float64
 13  kindergartenDistance  59202 non-null  float64
 14  restaurantDistance    59031 non-null  float64
 15  collegeDistance       57874 non-null  float64
 16  pharmacyDistance      59161 non-null  float64
 17  ownership             59246 non-null  object
 18  buildingMaterial      34306 non-null  object
 19  condition             14077 non-null  object
 20  hasParkingSpace       59246 non-null  object
 21  hasBalcony            59246 non-null  object
 22  hasElevator           56852 non-null  object
 23  hasSecurity           59246 non-null  object
 24  hasStorageRoom        59246 non-null  object
 25  price                 59246 non-null  int64
 26  date                  59246 non-null  object
dtypes: float64(16), int64(1), object(10)
memory usage: 12.7+ MB

In [18]:
df.describe()

,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,centreDistance,poiCount,schoolDistance,clinicDistance,postOfficeDistance,kindergartenDistance,restaurantDistance,collegeDistance,pharmacyDistance,price
count,59246.000000,59246.000000,50210.000000,58673.000000,53648.000000,59246.000000,59246.000000,59246.000000,59246.000000,59242.000000,58977.000000,59203.000000,59202.000000,59031.000000,57874.000000,59161.000000,5.924600e+04
mean,59.775264,2.687169,3.758952,6.199717,1989.002479,52.227829,21.008215,6.025616,22.529116,0.354674,0.828132,0.482847,0.272050,0.247822,1.545239,0.303056,1.023081e+06
std,22.658961,0.926591,2.919930,3.741757,28.583806,0.047292,0.063295,3.196114,21.960924,0.270334,0.850803,0.327786,0.208623,0.230125,1.160317,0.267990,4.547033e+05
min,25.000000,1.000000,1.000000,1.000000,1851.000000,52.104600,20.823898,0.020000,0.000000,0.004000,0.001000,0.001000,0.001000,0.001000,0.009000,0.001000,3.000000e+05
25%,43.870000,2.000000,2.000000,4.000000,1969.000000,52.194212,20.961720,3.680000,9.000000,0.176000,0.276000,0.255000,0.137000,0.097000,0.617000,0.136000,7.115538e+05
50%,55.100000,3.000000,3.000000,5.000000,1999.000000,52.229676,21.010930,5.850000,16.000000,0.285000,0.522000,0.417000,0.231000,0.185000,1.162000,0.230000,8.850000e+05
75%,70.100000,3.000000,5.000000,8.000000,2014.000000,52.253500,21.051727,8.050000,28.000000,0.445000,0.973000,0.630000,0.354000,0.321000,2.187000,0.386000,1.200000e+06
max,150.000000,6.000000,29.000000,29.000000,2024.000000,52.363708,21.249710,16.940000,136.000000,2.484000,4.999000,3.524000,2.271000,2.050000,5.000000,3.179000,3.250000e+06

In [19]:
df.isna().sum()

type                    14834
squareMeters                0
rooms                       0
floor                    9036
floorCount                573
buildYear                5598
latitude                    0
longitude                   0
centreDistance              0
poiCount                    0
schoolDistance              4
clinicDistance            269
postOfficeDistance         43
kindergartenDistance       44
restaurantDistance        215
collegeDistance          1372
pharmacyDistance           85
ownership                   0
buildingMaterial        24940
condition               45169
hasParkingSpace             0
hasBalcony                  0
hasElevator              2394
hasSecurity                 0
hasStorageRoom              0
price                       0
date                        0
dtype: int64